### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'MainModuleExecutor test #1_0'.

### ISSUE THREAD

**Issue by RomanSafe** [hyperskill/hs-test-python#14]
## Description
My source code works as I expected and finishes with code 0.
If I try to run test using [hs-test-python framework](https://github.com/hyperskill/hs-test-python), I would get an exception: ```RuntimeError: There is no current event loop in thread 'MainModuleExecutor test #1_0'.```

## Steps to Reproduce
My source code (simple_bot.py):
```python
import asyncio

from pyrogram import Client, filters

loop = asyncio.get_event_loop()


async def send_test(text):
    bot_username = "@Eng_vocabulary_bot"
    app = Client("my_account", api_id=my_api_id, api_hash=my_api_hash)
    async with app:
        await app.send_message(bot_username, text)
        async for message in app.search_messages(bot_username, limit=1):
            print(message.text)


loop.run_until_complete(send_test("TEST"))
loop.close()
```

The file with a test (tests.py):
```python
from hstest import dynamic_test, StageTest, TestedProgram, TestPassed


class SimpleBotTest(StageTest):
    @dynamic_test(time_limit=3000)
    def test(self):
        pr = TestedProgram()
        output = pr.start()
        if "TEST" in output:
            raise TestPassed



if __name__ == '__main__':
    SimpleBotTest().run_tests()
```
## Traceback
```python
Exception in test #1

Traceback (most recent call last):
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/Telegram_bot_for_english_learners/stage1/telegram_bot/simple_bot.py", line 3, in <module>
    from pyrogram import Client, filters
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/__init__.py", line 41, in <module>
    from .client import Client
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/client.py", line 44, in <module>
    from pyrogram.methods import Methods
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/__init__.py", line 25, in <module>
    from .messages import Messages
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/__init__.py", line 23, in <module>
    from .edit_inline_media import EditInlineMedia
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/edit_inline_media.py", line 25, in <module>
    from .inline_session import get_session
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/inline_session.py", line 27, in <module>
    lock = Lock()
RuntimeError: There is no current event loop in thread 'MainModuleExecutor test #1_0'.
Process finished with exit code 0
```
## How I tried to solve:
1. `loop = asyncio.new_event_loop(); asyncio.set_event_loop(loop)` instead of `loop = asyncio.get_event_loop()`
2. `app.run()`
3. `asyncio.run(main())`

## My questions
Is it possible to test asyncio applications with hs-test-python framework?
Do you have any idea how to solve this issue?

**Comment by aaaaaa2493** [comment]
@RomanSafe Hi!

I didn't know it was possible or impossible to test async applications using `hs-test-python` because we don't have such projects on Hyperskill yet. I'm sure we're going to have such projects at some point so thanks to you now I know that there are problems.

Let's investigate what causes `hs-test-python` to fail.

`asyncio.get_event_loop()` won't work because it requires the main thread to be executed in but the tested program is executed in a separate thread. I assume your traceback shows the problem when there's this line written.

What's wrong with `loop = asyncio.new_event_loop(); asyncio.set_event_loop(loop)`? Can you provide a traceback when there's this line written instead of the previous one?

Also, it would be great if you can provide source code without external dependencies (`from pyrogram import Client, filters`) checking which results in the same way so that I can run it myself and investigate the problem.

**Comment by RomanSafe** [comment]
> What's wrong with `loop = asyncio.new_event_loop(); asyncio.set_event_loop(loop)`? Can you provide a traceback when there's this line written instead of the previous one?

## The source code I used:
```python
import asyncio

from pyrogram import Client, filters


async def send_and_read_message(text: str) -> None:
    """Sends a message to a recipient_username and read it from.

    As recipient_username could be any username, mobile phone or "me" to send a message
    to yourself.

    :parameter text: the text of a message.

    """

    recipient_username = "@Eng_vocabulary_bot"
    app = Client("my_account", api_id=my_api_id, api_hash=my_api_hash)
    async with app:
        await app.send_message(recipient_username, text)
        async for message in app.search_messages(recipient_username, limit=1):
            print(message.text)


if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(send_and_read_message("TEST"))
    loop.close()
```
## I've got the next traceback:
```python
Exception in test #1

Traceback (most recent call last):
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/Telegram_bot_for_english_learners/stage1/telegram_bot/simple_bot_archive.py", line 3, in <module>
    from pyrogram import Client, filters
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/__init__.py", line 41, in <module>
    from .client import Client
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/client.py", line 44, in <module>
    from pyrogram.methods import Methods
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/__init__.py", line 25, in <module>
    from .messages import Messages
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/__init__.py", line 23, in <module>
    from .edit_inline_media import EditInlineMedia
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/edit_inline_media.py", line 25, in <module>
    from .inline_session import get_session
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/inline_session.py", line 27, in <module>
    lock = Lock()
RuntimeError: There is no current event loop in thread 'MainModuleExecutor test #1_0'.
Process finished with exit code 0
```
## Additional info
To run the code above you should replace my_api_id, my_api_hash with your own api_id and api_hash. An instruction about Quick Start with Pyrogram [here](https://docs.pyrogram.org/intro/quickstart).

**Comment by RomanSafe** [comment]
> Also, it would be great if you can provide source code without external dependencies (`from pyrogram import Client, filters`) checking which results in the same way so that I can run it myself and investigate the problem.

The main idea of my project is to create a Telegram bot for English learners. Without Pyrogram (or other high-level Python library) I have to use low-level Telegram API or TDLib which are not appropriate for learning purposes. Could we investigate the problem using Pyrogram (or other high-level Python library)?

**Comment by aaaaaa2493** [comment]
@RomanSafe 
It is really hard to investigate the problem when there are other libraries involved. All I suggest is to minimize the example where there's only async part left, so if the error can be reproduced then it is clear that there's an error with async. If async program works OK then there's error is `hs-test-python` and `pyprogram` interaction.

**Comment by RomanSafe** [comment]
I'd run a test of simplified code and the code passed the test.
## Simplified code:
```python
import asyncio


async def main(text: str, delay: int = 1) -> None:
    await asyncio.sleep(delay)
    print(text)


if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(main("TEST"))
    loop.close()
```
## Test:
```python
from hstest import dynamic_test, StageTest, TestedProgram, TestPassed


class AsyncFunctionTest(StageTest):
    @dynamic_test(time_limit=3000)
    def test(self):
        pr = TestedProgram("telegram_bot.simple_async_function")
        output = pr.start()
        if "TEST" in output:
            raise TestPassed


if __name__ == '__main__':
    AsyncFunctionTest().run_tests()
```
## Test results:
```
Start test 1
TEST

#educational_plugin test OK

Process finished with exit code 0
```

**Comment by RomanSafe** [comment]
And I'd run two simple coroutines concurrently. The code passed the test.
## Source code
```python
import asyncio
import time


async def say_after(delay: int, text: str) -> None:
    await asyncio.sleep(delay)
    print(text)


async def main():
    task1 = asyncio.create_task(say_after(1, 'hello'))
    task2 = asyncio.create_task(say_after(1, "TEST"))

    print(f"started at {time.strftime('%X')}")
    await task1
    await task2
    print(f"finished at {time.strftime('%X')}")

if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(main())
    loop.close()
```
## Test:
```python
from hstest import dynamic_test, StageTest, TestedProgram, TestPassed


class AsyncFunctionTest(StageTest):
    @dynamic_test(time_limit=3000)
    def test(self):
        pr = TestedProgram("telegram_bot.simple_async_function")
        output = pr.start()
        if "TEST" in output:
            raise TestPassed


if __name__ == '__main__':
    AsyncFunctionTest().run_tests()
```
## Test results:
```
Start test 1
started at 11:21:55
hello
TEST
finished at 11:21:56

#educational_plugin test OK

Process finished with exit code 0
```

**Comment by aaaaaa2493** [comment]
@RomanSafe 
So, the answer to the following question is "yes":

> Is it possible to test asyncio applications with hs-test-python framework?

Perhaps, it is an error with `hs-test-python` and `pyprogram` communication.

From the traceback, I can see that the error happens when importing `pyprogram` in line `from pyrogram import Client, filters`.
So maybe you need to create new event loop before importing `pyprogram` classes. Try the following code:

```python
import asyncio

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)

from pyrogram import Client, filters

async def send_test(text):
    bot_username = "@Eng_vocabulary_bot"
    app = Client("my_account", api_id=my_api_id, api_hash=my_api_hash)
    async with app:
        await app.send_message(bot_username, text)
        async for message in app.search_messages(bot_username, limit=1):
            print(message.text)


loop.run_until_complete(send_test("TEST"))
loop.close()
```

**Comment by RomanSafe** [comment]
@aaaaaa2493 Vladimir,
I've got the following traceback:
```
Traceback (most recent call last):
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/Telegram_bot_for_english_learners/stage1/telegram_bot/simple_bot.py", line 17, in <module>
    loop.run_until_complete(send_test("TEST"))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/Telegram_bot_for_english_learners/stage1/telegram_bot/simple_bot.py", line 11, in send_test
    async with app:
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/client.py", line 258, in __aenter__
    return await self.start()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 53, in start
    is_authorized = await self.connect()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/client.py", line 668, in load_session
    await self.storage.open()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/storage/file_storage.py", line 112, in open
    self.update()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/storage/file_storage.py", line 71, in update
    version = self.version()
  File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/storage/sqlite_storage.py", line 215, in version
    return self.conn.execute(
sqlite3.OperationalError: no such column: number

Process finished with exit code 1
```
I see the issue reason not in hs-test-python library.
 I'll continue to investigate this issue and take a look inside of pyrogram. Thank you!
